name: Generic System Image Builder

on:
  workflow_dispatch:
    
    
env:
  ROM_LINK: https://dl.google.com/dl/android/aosp/barbet-ota-sq3a.220705.003.a1-cb621def.zip
  ROM_TYPE: Generic
  BUILD_AB: true
  BUILD_AONLY: false
  ROM_AONLY: A.7z
  ROM_AB: AB.7z
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
       - name: Repo fetching...
         uses: actions/checkout@master
  # Cleanup The Actions Workspace Using Custom Composite Run Actions
       - name: Cleanup
         uses: rokibhasansagar/slimhub_actions@main
  # That's it! Now use your normal steps

       - name: Set Swap Space
         uses: pierotofy/set-swap-space@master
         with:
          swap-size-gb: 24
           
       - name: Setting up environment...
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk p7zip
       
       - name: Cloning repo...
         run: git clone --recurse-submodules https://github.com/ping2109/ErfanGSIs-TrebleExp.git ErfanGSIs
       
       - name: Installing requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Downloading rom and building A Only GSI
         if: env.BUILD_AONLY == 'true'
         run: sudo ./ErfanGSIs/url2GSI.sh -a $ROM_LINK $ROM_TYPE -d
       
       - name: 7zipping Aonly GSI
         if: env.BUILD_AONLY == 'true'
         run: 7za a -t7z -r $ROM_AONLY ErfanGSIs/output/*
       
       - name: Uploading Aonly GSI
         if: env.BUILD_AONLY == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer gof $ROM_AONLY
           
       - name: Cleaning output
         if: env.BUILD_AB == 'true'
         run: sudo rm -rf ErfanGSIs/output/*
         
       - name: Downloading rom and building A/B GSI
         if: env.BUILD_AB == 'true'
         run: sudo ./ErfanGSIs/url2GSI.sh -b $ROM_LINK $ROM_TYPE -d

       - name: 7zipping AB GSI
         if: env.BUILD_AB == 'true'
         run: 7za a -t7z -r $ROM_AB ErfanGSIs/output/*

       - name: Uploading AB 
         if: env.BUILD_AB == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer gof $ROM_AB
              
           
